// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import Chart from 'stimulus-chartjs'
import Notification from 'stimulus-notification'

application.register('notification', Notification)
application.register('chart', Chart)

import EditNotesController from "./edit_notes_controller"
application.register("edit-notes", EditNotesController)

import AddTaskController from "./add_task_controller"
application.register("add-task", AddTaskController)

import DoneTaskController from "./done_task_controller"
application.register("done-task", DoneTaskController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import ShowArrowController from "./show_arrow_controller"
application.register("show-arrow", ShowArrowController)

// import UserSubscriptionController from "./user_subscription_controller"
// application.register("user_subscription", UserSubscriptionController)

import UserController from "./user_controller"
application.register("user", UserController)


// import { application } from '@hotwired/stimulus'
import Popover from 'stimulus-popover'
import BadgesController from "./badges_controller"

application.register('badges', BadgesController)

import UpdateStatusController from "./update_status_controller"
application.register("update-status", UpdateStatusController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)
