// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditNotesController from "./edit_notes_controller"
application.register("edit-notes", EditNotesController)

import AddTaskController from "./add_task_controller"
application.register("add-task", AddTaskController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
